# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("https://ceshiren.com/")
    self.driver.set_window_size(1058, 820)
    self.driver.find_element(By.LINK_TEXT, "热门").click()
    self.driver.find_element(By.LINK_TEXT, "关于mock实战作业").click()
    self.driver.execute_script("window.scrollTo(0,327.20001220703125)")
    self.driver.execute_script("window.scrollTo(0,1297.5999755859375)")
    self.driver.execute_script("window.scrollTo(0,3859.199951171875)")
    self.driver.find_element(By.LINK_TEXT, "如何更好的在UI自动化测试过程中协助开发定位问题，比如UI点击无效时抓取当时系统的debug日志啥的，老师们可以帮忙介绍下么？").click()
    self.driver.execute_script("window.scrollTo(0,0)")
